// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sin_estimate_NumericVector
NumericVector sin_estimate_NumericVector(NumericVector x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_estimate_NumericVector(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_estimate_NumericVector(x, tmin, tmax));
    return __result;
END_RCPP
}
// sin_int_estimate_NumericVector
NumericVector sin_int_estimate_NumericVector(NumericVector x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_int_estimate_NumericVector(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_int_estimate_NumericVector(x, tmin, tmax));
    return __result;
END_RCPP
}
// sin_poly_temp_one
double sin_poly_temp_one(double tmin, double tmax, double degree, double weight);
RcppExport SEXP degreedays_sin_poly_temp_one(SEXP tminSEXP, SEXP tmaxSEXP, SEXP degreeSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< double >::type weight(weightSEXP);
    __result = Rcpp::wrap(sin_poly_temp_one(tmin, tmax, degree, weight));
    return __result;
END_RCPP
}
// sin_poly_temp
NumericVector sin_poly_temp(NumericVector tmin, NumericVector tmax, double degree, NumericVector weights);
RcppExport SEXP degreedays_sin_poly_temp(SEXP tminSEXP, SEXP tmaxSEXP, SEXP degreeSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    __result = Rcpp::wrap(sin_poly_temp(tmin, tmax, degree, weights));
    return __result;
END_RCPP
}
// sin_poly_temp_par
NumericMatrix sin_poly_temp_par(NumericVector tmin, NumericVector tmax, NumericVector degree, NumericVector weights);
RcppExport SEXP degreedays_sin_poly_temp_par(SEXP tminSEXP, SEXP tmaxSEXP, SEXP degreeSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    __result = Rcpp::wrap(sin_poly_temp_par(tmin, tmax, degree, weights));
    return __result;
END_RCPP
}
// sin_estimate
double sin_estimate(double x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_estimate(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_estimate(x, tmin, tmax));
    return __result;
END_RCPP
}
// sin_int_estimate
double sin_int_estimate(double x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_int_estimate(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_int_estimate(x, tmin, tmax));
    return __result;
END_RCPP
}
// degree_days_one
double degree_days_one(double t0, double t1, double tmin, double tmax, double weight);
RcppExport SEXP degreedays_degree_days_one(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type weight(weightSEXP);
    __result = Rcpp::wrap(degree_days_one(t0, t1, tmin, tmax, weight));
    return __result;
END_RCPP
}
// degree_days_band_daily
NumericMatrix degree_days_band_daily(NumericVector t0, NumericVector t1, NumericVector tmin, NumericVector tmax, NumericVector weights);
RcppExport SEXP degreedays_degree_days_band_daily(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    __result = Rcpp::wrap(degree_days_band_daily(t0, t1, tmin, tmax, weights));
    return __result;
END_RCPP
}
// degree_days_band_daily_par
NumericMatrix degree_days_band_daily_par(NumericVector t0, NumericVector t1, NumericVector tmin, NumericVector tmax, NumericVector weights);
RcppExport SEXP degreedays_degree_days_band_daily_par(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    __result = Rcpp::wrap(degree_days_band_daily_par(t0, t1, tmin, tmax, weights));
    return __result;
END_RCPP
}
// days_in_bin_one
double days_in_bin_one(double t0, double t1, double tmin, double tmax, double weight);
RcppExport SEXP degreedays_days_in_bin_one(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< double >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< double >::type weight(weightSEXP);
    __result = Rcpp::wrap(days_in_bin_one(t0, t1, tmin, tmax, weight));
    return __result;
END_RCPP
}
// days_in_bin_daily
NumericMatrix days_in_bin_daily(NumericVector t0, NumericVector t1, NumericVector tmin, NumericVector tmax, NumericVector weights);
RcppExport SEXP degreedays_days_in_bin_daily(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    __result = Rcpp::wrap(days_in_bin_daily(t0, t1, tmin, tmax, weights));
    return __result;
END_RCPP
}
// days_in_bin_daily_par
NumericMatrix days_in_bin_daily_par(NumericVector t0, NumericVector t1, NumericVector tmin, NumericVector tmax, NumericVector weights);
RcppExport SEXP degreedays_days_in_bin_daily_par(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    __result = Rcpp::wrap(days_in_bin_daily_par(t0, t1, tmin, tmax, weights));
    return __result;
END_RCPP
}
// parInnProd
double parInnProd(NumericVector x, NumericVector y);
RcppExport SEXP degreedays_parInnProd(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    __result = Rcpp::wrap(parInnProd(x, y));
    return __result;
END_RCPP
}
