// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sin_estimate_NumericVector
NumericVector sin_estimate_NumericVector(NumericVector x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_estimate_NumericVector(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_estimate_NumericVector(x, tmin, tmax));
    return __result;
END_RCPP
}
// sin_int_estimate_NumericVector
NumericVector sin_int_estimate_NumericVector(NumericVector x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_int_estimate_NumericVector(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_int_estimate_NumericVector(x, tmin, tmax));
    return __result;
END_RCPP
}
// sin_estimate
double sin_estimate(double x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_estimate(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_estimate(x, tmin, tmax));
    return __result;
END_RCPP
}
// sin_int_estimate
double sin_int_estimate(double x, double tmin, double tmax);
RcppExport SEXP degreedays_sin_int_estimate(SEXP xSEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(sin_int_estimate(x, tmin, tmax));
    return __result;
END_RCPP
}
// degree_days_band
NumericVector degree_days_band(NumericVector t0, NumericVector t1, double tmin, double tmax);
RcppExport SEXP degreedays_degree_days_band(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(degree_days_band(t0, t1, tmin, tmax));
    return __result;
END_RCPP
}
// days_in_bin
NumericVector days_in_bin(NumericVector t0, NumericVector t1, double tmin, double tmax);
RcppExport SEXP degreedays_days_in_bin(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< double >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< double >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(days_in_bin(t0, t1, tmin, tmax));
    return __result;
END_RCPP
}
// days_in_bin_daily
NumericMatrix days_in_bin_daily(NumericVector t0, NumericVector t1, NumericVector tmin, NumericVector tmax);
RcppExport SEXP degreedays_days_in_bin_daily(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(days_in_bin_daily(t0, t1, tmin, tmax));
    return __result;
END_RCPP
}
// degree_days_band_daily
NumericMatrix degree_days_band_daily(NumericVector t0, NumericVector t1, NumericVector tmin, NumericVector tmax);
RcppExport SEXP degreedays_degree_days_band_daily(SEXP t0SEXP, SEXP t1SEXP, SEXP tminSEXP, SEXP tmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t1(t1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmin(tminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tmax(tmaxSEXP);
    __result = Rcpp::wrap(degree_days_band_daily(t0, t1, tmin, tmax));
    return __result;
END_RCPP
}
