# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sin_estimate_NumericVector <- function(x, tmin, tmax) {
    .Call('degreedays_sin_estimate_NumericVector', PACKAGE = 'degreedays', x, tmin, tmax)
}

sin_int_estimate_NumericVector <- function(x, tmin, tmax) {
    .Call('degreedays_sin_int_estimate_NumericVector', PACKAGE = 'degreedays', x, tmin, tmax)
}

sin_estimate <- function(x, tmin, tmax) {
    .Call('degreedays_sin_estimate', PACKAGE = 'degreedays', x, tmin, tmax)
}

sin_int_estimate <- function(x, tmin, tmax) {
    .Call('degreedays_sin_int_estimate', PACKAGE = 'degreedays', x, tmin, tmax)
}

degree_days_band <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_degree_days_band', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

days_in_bin <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_days_in_bin', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

#' @title Calculate days in bin for daily data.
#' @description Calculate days in bin for daily data using C++ code.
#' @param t0 vector of lower bounds
#' @param t1 vector of upper bounds
#' @param tmin vector of tmin values (1 per day)
#' @param tmax vector of tmax values (1 per day)
#' @return num_days x num_bins \code{matrix}
days_in_bin_daily <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_days_in_bin_daily', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

#' @title Calculate degree days for daily data.
#' @description Calculate degree days for daily data using C++ code.
#' @param t0 vector of lower bounds
#' @param t1 vector of upper bounds
#' @param tmin vector of tmin values (1 per day)
#' @param tmax vector of tmax values (1 per day)
#' @return num_days x num_bins \code{matrix}
degree_days_band_daily <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_degree_days_band_daily', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

