# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Sine function with max and min given.
#' @description Sine function evaluated at x for single sine interpolation.
#' @param x Vector of x values in [0, 1] to evaluate at.
#' @param tmin \code{double} tmin value.
#' @param tmax \code{double} tmax value.
#' @return Vector of interpolated sine values.
sin_estimate_NumericVector <- function(x, tmin, tmax) {
    .Call('degreedays_sin_estimate_NumericVector', PACKAGE = 'degreedays', x, tmin, tmax)
}

sin_int_estimate_NumericVector <- function(x, tmin, tmax) {
    .Call('degreedays_sin_int_estimate_NumericVector', PACKAGE = 'degreedays', x, tmin, tmax)
}

sin_estimate <- function(x, tmin, tmax) {
    .Call('degreedays_sin_estimate', PACKAGE = 'degreedays', x, tmin, tmax)
}

sin_int_estimate <- function(x, tmin, tmax) {
    .Call('degreedays_sin_int_estimate', PACKAGE = 'degreedays', x, tmin, tmax)
}

degree_days_one <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_degree_days_one', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

#' @title Calculate degree days for daily data.
#' @description Calculate degree days for daily data using C++ code.
#' @param t0 vector of lower bounds
#' @param t1 vector of upper bounds
#' @param tmin vector of tmin values (1 per day)
#' @param tmax vector of tmax values (1 per day)
#' @return num_days x num_bins \code{matrix}
degree_days_band_daily <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_degree_days_band_daily', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

degree_days_band_daily_par <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_degree_days_band_daily_par', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

days_in_bin_one <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_days_in_bin_one', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

#' @title Calculate days in bin for daily data.
#' @description Calculate days in bin for daily data using C++ code.
#' @param t0 vector of lower bounds
#' @param t1 vector of upper bounds
#' @param tmin vector of tmin values (1 per day)
#' @param tmax vector of tmax values (1 per day)
#' @return num_days x num_bins \code{matrix}
days_in_bin_daily <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_days_in_bin_daily', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

days_in_bin_daily_par <- function(t0, t1, tmin, tmax) {
    .Call('degreedays_days_in_bin_daily_par', PACKAGE = 'degreedays', t0, t1, tmin, tmax)
}

